### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by berezovskyi** [berezovskyi/sparqles#68]
```
sparqles_backend-svc_1  | 14-10-24 21:00:34 [ INFO] sparqles.core.EndpointTask:57 - EXECUTE ATask(http://http://opendata.intellidomo.es:8080/sparql/)
sparqles_backend-svc_1  | 14-10-24 21:00:34 [ INFO] sparqles.utils.ExceptionHandler:66 - EXC@1#46074
sparqles_backend-svc_1  | HttpException: -1 Unexpected error making the query: GET http://http://opendata.intellidomo.es:8080/sparql/?query=SELECT%20?s%20WHERE%7B?s%20?p%20?o%7D%20LIMIT%201
sparqles_backend-svc_1  |       at org.apache.jena.sparql.engine.http.QueryExceptionHTTP.rewrap(QueryExceptionHTTP.java:52)
sparqles_backend-svc_1  |       at org.apache.jena.sparql.exec.http.QueryExecHTTP.executeQuery(QueryExecHTTP.java:552)
sparqles_backend-svc_1  |       at org.apache.jena.sparql.exec.http.QueryExecHTTP.execRowSet(QueryExecHTTP.java:173)
sparqles_backend-svc_1  |       at org.apache.jena.sparql.exec.http.QueryExecHTTP.select(QueryExecHTTP.java:164)
sparqles_backend-svc_1  |       at org.apache.jena.sparql.exec.QueryExecutionAdapter.execSelect(QueryExecutionAdapter.java:108)
sparqles_backend-svc_1  |       at sparqles.core.availability.ATask.testSelect(ATask.java:89)
sparqles_backend-svc_1  |       at sparqles.core.availability.ATask.process(ATask.java:76)
sparqles_backend-svc_1  |       at sparqles.core.availability.ATask.process(ATask.java:27)
sparqles_backend-svc_1  |       at sparqles.core.EndpointTask.call(EndpointTask.java:67)
sparqles_backend-svc_1  |       at sparqles.core.EndpointTask.call(EndpointTask.java:19)
sparqles_backend-svc_1  |       at sparqles.schedule.Scheduler$SchedulerTimerTask.run(Scheduler.java:266)
sparqles_backend-svc_1  |       at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
sparqles_backend-svc_1  |       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
sparqles_backend-svc_1  |       at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
sparqles_backend-svc_1  |       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
sparqles_backend-svc_1  |       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
sparqles_backend-svc_1  |       at java.base/java.lang.Thread.run(Thread.java:1583)
sparqles_backend-svc_1  | Caused by: java.io.IOException: selector manager closed
sparqles_backend-svc_1  |       at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:964)
sparqles_backend-svc_1  |       at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
sparqles_backend-svc_1  |       at org.apache.jena.http.HttpLib.executeJDK(HttpLib.java:610)
sparqles_backend-svc_1  |       at org.apache.jena.http.auth.AuthLib.authExecute(AuthLib.java:51)
sparqles_backend-svc_1  |       at org.apache.jena.http.HttpLib.execute(HttpLib.java:570)
sparqles_backend-svc_1  |       at org.apache.jena.http.HttpLib.execute(HttpLib.java:527)
sparqles_backend-svc_1  |       at org.apache.jena.sparql.exec.http.QueryExecHTTP.executeQuery(QueryExecHTTP.java:548)
sparqles_backend-svc_1  |       ... 15 more
sparqles_backend-svc_1  | Caused by: java.io.IOException: selector manager closed
sparqles_backend-svc_1  |       at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.selectorClosedException(HttpClientImpl.java:1126)
sparqles_backend-svc_1  |       at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:1005)
sparqles_backend-svc_1  |       at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:930)
sparqles_backend-svc_1  |       ... 21 more
sparqles_backend-svc_1  | Caused by: java.lang.OutOfMemoryError: Java heap space
sparqles_backend-svc_1  | 14-10-24 21:00:34 [ INFO] sparqles.utils.ExceptionHandler:66 - EXC@1#46075
sparqles_backend-svc_1  | HttpException: -1 Unexpected error making the query: GET http://http://opendata.intellidomo.es:8080/sparql/?query=SELECT%20?s%20WHERE%7B?s%20?p%20?o%7D%20LIMIT%201
sparqles_backend-svc_1  |       at org.apache.jena.sparql.engine.http.QueryExceptionHTTP.rewrap(QueryExceptionHTTP.java:52)
sparqles_backend-svc_1  |       at org.apache.jena.sparql.exec.http.QueryExecHTTP.executeQuery(QueryExecHTTP.java:552)
sparqles_backend-svc_1  |       at org.apache.jena.sparql.exec.http.QueryExecHTTP.execRowSet(QueryExecHTTP.java:173)
sparqles_backend-svc_1  |       at org.apache.jena.sparql.exec.http.QueryExecHTTP.select(QueryExecHTTP.java:164)
sparqles_backend-svc_1  |       at org.apache.jena.sparql.exec.QueryExecutionAdapter.execSelect(QueryExecutionAdapter.java:108)
sparqles_backend-svc_1  |       at sparqles.core.availability.ATask.testSelect(ATask.java:89)
sparqles_backend-svc_1  |       at sparqles.core.availability.ATask.process(ATask.java:76)
sparqles_backend-svc_1  |       at sparqles.core.availability.ATask.process(ATask.java:27)
sparqles_backend-svc_1  |       at sparqles.core.EndpointTask.call(EndpointTask.java:67)
sparqles_backend-svc_1  |       at sparqles.core.EndpointTask.call(EndpointTask.java:19)
sparqles_backend-svc_1  |       at sparqles.schedule.Scheduler$SchedulerTimerTask.run(Scheduler.java:266)
sparqles_backend-svc_1  |       at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
sparqles_backend-svc_1  |       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
sparqles_backend-svc_1  |       at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
sparqles_backend-svc_1  |       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
sparqles_backend-svc_1  |       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
sparqles_backend-svc_1  |       at java.base/java.lang.Thread.run(Thread.java:1583)
sparqles_backend-svc_1  | Caused by: java.io.IOException: selector manager closed
sparqles_backend-svc_1  |       at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:964)
sparqles_backend-svc_1  |       at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
sparqles_backend-svc_1  |       at org.apache.jena.http.HttpLib.executeJDK(HttpLib.java:610)
sparqles_backend-svc_1  |       at org.apache.jena.http.auth.AuthLib.authExecute(AuthLib.java:51)
sparqles_backend-svc_1  |       at org.apache.jena.http.HttpLib.execute(HttpLib.java:570)
sparqles_backend-svc_1  |       at org.apache.jena.http.HttpLib.execute(HttpLib.java:527)
sparqles_backend-svc_1  |       at org.apache.jena.sparql.exec.http.QueryExecHTTP.executeQuery(QueryExecHTTP.java:548)
sparqles_backend-svc_1  |       ... 15 more
sparqles_backend-svc_1  | Caused by: java.io.IOException: selector manager closed
sparqles_backend-svc_1  |       at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.selectorClosedException(HttpClientImpl.java:1126)
sparqles_backend-svc_1  |       at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:1005)
sparqles_backend-svc_1  |       at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:930)
sparqles_backend-svc_1  |       ... 21 more
sparqles_backend-svc_1  | Caused by: java.lang.OutOfMemoryError: Java heap space
sparqles_backend-svc_1  | 14-10-24 21:00:34 [ WARN] sparqles.core.availability.ATask:157 - failed SELECT query for http://http://opendata.intellidomo.es:8080/sparql/, EXC@1#46075> QueryExceptionHTTP msg:Unexpected error making the query: GET http://http://opendata.intellidomo.es:8080/sparql/?query=SELECT%20?s%20WHERE%7B?s%20?p%20?o%7D%20LIMIT%201 cause:java.io.IOException: selector manager closed
```

**Comment by berezovskyi** [comment]
There is likely some leak because it's not the response size - the URI is NXDOMAIN:

```
curl -I http://opendata.intellidomo.es:8080/sparql/\?query\=SELECT%20\?s%20WHERE%7B\?s%20\?p%20\?o%7D%20LIMIT%201
curl: (6) Could not resolve host: opendata.intellidomo.es
```

**Comment by berezovskyi** [comment]
Also see https://github.com/OpenLinkSoftware/sparqles/commit/db897e8449e12a627a675229478573c41a42a9b7

**Comment by berezovskyi** [comment]
https://github.com/berezovskyi/sparqles/commit/48cd85447e48530190c963966103ccefc12fccb7

**Comment by berezovskyi** [comment]
Should be fixed in v0.4.0
